arrowParens: "avoid"
htmlWhitespaceSensitivity: "ignore"
proseWrap: "always"
bracketSameLine: true
singleAttributePerLine: true
useTabs: false
semi: false

# Svelte
svelteSortOrder: "options-styles-scripts-markup"
svelteStrictMode: false
svelteIndentScriptAndStyle: true
svelteAllowShorthand: true

# Astro
astroAllowShorthand: true

plugins:
  - prettier-plugin-svelte
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss

overrides:
  # Svelte
  - files: "*.svelte"
    options:
      parser: "svelte"
  # Astro
  - files: "*.astro"
    options:
      parser: "astro"
